name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
        poetry-version: ["1.7.1"]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run image
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
      run: |
        RUN poetry export -f requirements.txt --without-hashes --only main -o requirements.txt
        RUN pip install -r requirements.txt
        RUN rm requirements.txt
    - name: Run Checks
      run: |
        python manage.py check
        python manage.py check --deploy
